package com.armjld.rayashipping.Settings;

import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.text.HtmlCompat;

import com.armjld.rayashipping.R;


public class Terms extends AppCompatActivity {

    @Override
    public void onBackPressed() {
        finish();
    }

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_terms);

        TextView txtTerms = findViewById(R.id.txtTerms);
        ImageView btnBack = findViewById(R.id.btnBack);
        txtTerms.setMovementMethod(new ScrollingMovementMethod());
        btnBack.setOnClickListener(v-> finish());
        String privcyCode = "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:center;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>الشروط والاحكام</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>بمجرد استخدامك لمنصة التشغيل والابلكيشن الخاصة بشركة إشحنلي فهذا يعد بمثابة موافقة علي جميع الاحكام والشروط والخصوصية المذكورة والمنصوص عليها من قبل الشركة .</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>شركة إشحنلي هي منصة الكترونية &nbsp;مجانيه لتوصيل الراسل بكابتن التوصيل وهي ليست شركة شحن او نقل او بريد سريع .</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ولذلك الشركة غير مسولة عن تصرفات اي من اطراف المستخدمين للابلكيشن او المنصة الالكترونية</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>وكابتن التوصيل والراسل والمرسل الية كلا مسول عن تصرفاته كليا و جزئيا &nbsp;سواء اكانت مدنية او جنائية&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>وسواء مع بعضهم البعض او مع المجتمع والاخرين وهم وحدهم كلا علي حده مسوال عن جميع تصرفاته&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>في حالة وجود مشكلة بين اي من اطراف المستخدمين لخدمات الشركة &nbsp;مع بعضهم البعض او مع الاخرين او مع الدولة باي من موسساتها&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>يحق للشركط تقديم كافة ما لديها من مستندات الي النيابة العامة في حالة طلب منها ذلك&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>لا يحق لاي طرف من الاطراف المستخدمة للمنصة او الابلكيشن او المستفيدين منها بطريقة مباشرة او غير مباشرة مقاضاة الشركة لاي تصرف او جريمة باي من انواها واشكالها او حتي عمل مسئ اتجاه اي فرد او شخص اعتباري او مؤسسة من موسسات الدولة &nbsp;وهو وحده من يسال عن تصرفه طبقا للقوانين المنظمة للبلد .</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>لا يحق للراسل استخدام المنصة او الابلكيشن في ارسال طلب او شئ مخالف نقله او بيعه او تداولة داخل جمهورية مصر العربية وهو وحده من يسال عن ذلك التصرف في حالة اختراقة او مخالفته للقوانين&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>وهو مسؤل وحده عن محتويات الطلب مسولية كاملة .</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>الشركة غير مسؤلة عن تراخيص المعدة المستخدمة من قبل كابتن التوصيل سواء اكانت ملكيته ملكيه خاصة او مملوكة للغير&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>في حالة استلام الطلب من الراسل في حالة سليمة وتم فقده او جزء منه او تلف او سرق او كسر يتحمل الكابتن ثمن الطلب كاملا وتعويض الراسل عنه&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>بمجرد استلام كابتن لتوصيل الطلب من الراسل علي الابلكيشن فهو بمثابة &nbsp;دليل استلام يعتد به&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>في حالة وجود شكوي من اي طرف للاخر بخصوص سوء استخدام الخدمة وتم التحقق واثباتها سوف يتم اغلاق الحساب الخاص بك فورا ومنعك من استخدام المنصة او الابلكيشن الخاص بالشركة&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>يحق للشركة بايقاف الخدمة او منعها لاي طرف قد تري من وجه نظرها بانه يسي استخدام الخدمة وذلك بدون تقديم اي مسببات او اعزار او اشعارات&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:center;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>سياسة الخصوصية</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>التعامل علي الابكيشن علي مسؤليتك الخاصه</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>و اتبع خطوات السلامة في التعامل مع الطرف الاخر</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>كابتن التوصيل يتسلم الطلبات / الاوردرات من محل سكن التاجر او مكتبة</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>او شركته فقط</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>و يقوم الراسل بتحصيل ثمن الطلب قبل تسليم الاوردر للكابتن</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ويقوم كابتن التوصيل بفحص الطلب ومحتوياته قبل الاستلام للتاكد من سلامته&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>في حالة رفض الطلب من قبل المرسل الية وتم تاكيد ذلك لابد من ارجاع الطلب في اسرع وقت الي الراسل واسترداد قيمة الطلب التي قد تم دفعها مسبقا من قبل كابتن التوصيل مع الزام الراسل بتحمل مصاريف التوصيل الموضحه علي الابلكيشن</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>و ذلك حرصا علي ضمان حق كلا الطرفين</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>و مطور البرنامج غير مسؤل عن اي اوردر/حموله او من يوصلها او من يتاجر بها</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">. &nbsp;+</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>قام</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>شركة إشحنلي</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ببناء تطبيق</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>إشحنلي</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>باعتباره تطبيقًا مجانيًا. يتم توفير هذه الخدمة من قبل</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>إشحنلي</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>دون أي تكلفة وهي مخصصة للاستخدام كما هي</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>تُستخدم هذه الصفحة لإبلاغ الزائرين بشأن سياساتي فيما يتعلق بجمع المعلومات الشخصية واستخدامها والكشف عنها إذا قرر أي شخص استخدام الخدمة الخاصة بي</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>إذا اخترت استخدام الخدمة الخاصة بشركة إشحنلي ، فأنت توافق على جمع المعلومات واستخدامها فيما يتعلق بهذه السياسة. تُستخدم المعلومات الشخصية التي أقوم بجمعها لتوفير الخدمة وتحسينها. لن أستخدم أو أشارك معلوماتك مع أي شخص باستثناء ما هو موضح في سياسة الخصوصية هذه</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>المصطلحات المستخدمة في سياسة الخصوصية هذه لها نفس المعاني الموجودة في الشروط والأحكام الخاصة بنا ، والتي يمكن الوصول إليها في</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ابلكيشن إشحنلي</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ما لم يتم تحديد خلاف ذلك في سياسة الخصوصية هذه</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>جمع المعلومات واستخدامها</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>للحصول على تجربة أفضل ، أثناء استخدام خدمتنا ، قد أطلب منك أن تزودنا ببعض المعلومات الشخصية المحددة للهوية ، بما في ذلك على سبيل المثال لا الحصر البريد الإلكتروني والاسم والهاتف والمواقع. سيتم الاحتفاظ بالمعلومات التي أطلبها على جهازك ولن أقوم بجمعها بأي شكل من الأشكال</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>يستخدم التطبيق خدمات الطرف الثالث التي قد تجمع المعلومات المستخدمة لتحديد هويتك</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>رابط إلى سياسة الخصوصية لموفري خدمة الطرف الثالث المستخدمة من قبل التطبيق</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>خدمات</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;Google Play&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>خدمات&nbsp;</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">apple store</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>تسجيل البيانات</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>أريد أن أبلغك أنه كلما استخدمت خدمتنا ، في حالة وجود خطأ في التطبيق ، نقوم بجمع البيانات والمعلومات (من خلال منتجات الطرف الثالث) على هاتفك تسمى</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;Log Data.&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>قد تتضمن بيانات السجل هذه معلومات مثل عنوان بروتوكول الإنترنت</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;( IP &nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>الخاص بجهازك ، واسم الجهاز ، وإصدار نظام التشغيل ، وتكوين التطبيق عند استخدام الخدمة الخاصة بي ، ووقت وتاريخ استخدامك للخدمة ، وإحصاءات أخرى</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ملفات التعريف</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ملفات تعريف الارتباط هي ملفات تحتوي على كمية صغيرة من البيانات التي يتم استخدامها بشكل شائع كمعرفات فريدة مجهولة الهوية. يتم إرسالها إلى متصفحك من مواقع الويب التي تزورها ويتم تخزينها على الذاكرة الداخلية لجهازك</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>لا تستخدم هذه الخدمة &nbsp;ملفات تعريف الارتباط &nbsp;هذه بشكل صريح. ومع ذلك ، قد يستخدم التطبيق كودًا ومكتبات تابعة لجهة خارجية تستخدم &nbsp; ملفات تعريف الارتباط &nbsp;لجمع المعلومات وتحسين خدماتها. لديك خيار إما قبول أو رفض ملفات تعريف الارتباط هذه ومعرفة متى يتم إرسال ملف تعريف ارتباط إلى جهازك. إذا اخترت رفض ملفات تعريف الارتباط الخاصة بنا ، فقد لا تتمكن من استخدام بعض أجزاء هذه الخدمة</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>مقدمي الخدمة</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>يجوز لي توظيف شركات وأفراد من جهات خارجية للأسباب التالية</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">:&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>لتسهيل خدمتنا ؛</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>لتقديم الخدمة نيابة عنا ؛</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>لأداء الخدمات المتعلقة بالخدمة ؛ أو</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>ل</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>مساعدتنا في تحليل كيفية استخدام خدمتنا</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>أريد إبلاغ مستخدمي هذه الخدمة أن هذه الأطراف الثالثة يمكنها الوصول إلى معلوماتك الشخصية. والسبب هو أداء المهام المسندة إليهم نيابة عنا. ومع ذلك ، فإنهم ملزمون بعدم الكشف عن المعلومات أو استخدامها لأي غرض آخر</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>الأمان</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>أقدر ثقتك في تزويدنا بمعلوماتك الشخصية ، وبالتالي نسعى جاهدين لاستخدام وسائل مقبولة تجاريًا لحمايتها. ولكن تذكر أنه لا توجد طريقة إرسال عبر الإنترنت ، أو طريقة تخزين إلكترونية آمنة وموثوق بها بنسبة 100٪ ، ولا يمكنني ضمان أمانها المطلق</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>روابط لمواقع أخرى</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>قد تحتوي هذه الخدمة على روابط لمواقع أخرى. إذا قمت بالنقر فوق ارتباط جهة خارجية ، فسيتم توجيهك إلى هذا الموقع. لاحظ أن هذه المواقع الخارجية لا أديرها. لذلك ، أنصحك بشدة بمراجعة سياسة الخصوصية لهذه المواقع. ليس لدي أي سيطرة ولا أتحمل أي مسؤولية عن المحتوى أو سياسات الخصوصية أو الممارسات الخاصة بأي مواقع أو خدمات تابعة لجهات خارجية</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>خصوصية الأطفال</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>لا تتعامل هذه الخدمات مع أي شخص يقل عمره عن 13 عامًا. لا أقوم بجمع معلومات التعريف الشخصية عن عمد من الأطفال تحت سن 13 عامًا. في حالة اكتشاف أن طفلاً دون 13 عامًا قد زودني بمعلومات شخصية ، فإنني أحذفها على الفور من خوادمنا. إذا كنت أحد الوالدين أو الوصي وكنت على علم بأن طفلك قدم لنا معلومات شخصية ، يرجى الاتصال بي حتى أتمكن من القيام بالإجراءات اللازمة</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>التغييرات على سياسة الخصوصية هذه</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>قد أقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. وبالتالي ، ننصحك بمراجعة هذه الصفحة بشكل دوري لأية تغييرات. سأعلمك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">.&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>تسري هذه السياسة اعتبارًا من 2020-05-21</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span><span style='font-size:19px;line-height:115%;font-family:\"Arial\",sans-serif;'>اتصل بنا 01551542514</span><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>\n" +
                "<p dir=\"RTL\" style='margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:15px;font-family:\"Calibri\",sans-serif;text-align:right;'><span dir=\"LTR\" style=\"font-size:19px;line-height:115%;\">&nbsp;</span></p>";
        // get the terms of the app
        txtTerms.setText(HtmlCompat.fromHtml(privcyCode, 0));

        // Tool Bar Title
        TextView toolbar_title = findViewById(R.id.toolbar_title);
        toolbar_title.setText("الشروط و الاحكام");
    }
}
